"""
ai/quiz_generator.py - Grounded AI Assessment & Quiz Generator.

Generates rigorous, educational, multiple-choice quizzes grounded strictly
in lesson educational content.
- Uses Google Gemini (via call_gemini_json) with structured JSON enforcement.
- Provides a robust deterministic offline fallback when Gemini is unavailable,
  unconfigured, rate-limited (HTTP 429), or when test mode is active.
"""

import json
import logging
import os
import re
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field, field_validator, model_validator

from .llm_client import call_gemini_json, get_gemini_config, LLMKeyMissingError, LLMError

logger = logging.getLogger("lms.ai.quiz_generator")


class QuizGenerationError(Exception):
    """Raised when quiz generation fails or output cannot be validated."""
    pass


# ---------------------------------------------------------------------------
# Pydantic Schemas for Internal Validation
# ---------------------------------------------------------------------------

class GeneratedQuestion(BaseModel):
    """Represents a validated question generated by AI or deterministic fallback."""
    question_text: str = Field(..., min_length=5, description="Question prompt")
    question_type: str = Field(default="multiple_choice", description="Question type")
    options: List[str] = Field(..., description="List of exactly 4 choices")
    correct_answer: str = Field(..., description="The correct answer matching one of the options")
    explanation: str = Field(..., min_length=5, description="Pedagogical explanation")
    points: int = Field(default=1, ge=1, description="Point value")
    difficulty: str = Field(default="medium", description="Question difficulty")
    concept: Optional[str] = Field(None, description="Domain concept tested")
    order_number: int = Field(default=1, ge=1, description="Display sequence order")

    @field_validator("options")
    @classmethod
    def validate_options(cls, v: Any) -> List[str]:
        if not isinstance(v, list) or len(v) != 4:
            raise ValueError(f"Question must have exactly 4 options; received {len(v) if isinstance(v, list) else type(v)}")
        cleaned = [str(opt).strip() for opt in v if str(opt).strip()]
        if len(cleaned) != 4:
            raise ValueError("All 4 options must be non-empty strings.")
        # Ensure all 4 options are unique
        if len(set(opt.lower() for opt in cleaned)) != 4:
            raise ValueError(f"All 4 options must be unique; received: {cleaned}")
        return cleaned

    @model_validator(mode="after")
    def validate_correct_answer_in_options(self) -> "GeneratedQuestion":
        target = self.correct_answer.strip()
        # Direct exact match
        for opt in self.options:
            if opt == target:
                self.correct_answer = opt
                return self
        # Case-insensitive match fallback
        for opt in self.options:
            if opt.lower() == target.lower():
                self.correct_answer = opt
                return self
        raise ValueError(
            f"correct_answer '{self.correct_answer}' does not match any of the 4 options: {self.options}"
        )


class GeneratedQuiz(BaseModel):
    """Complete validated quiz structure ready for database persistence."""
    title: str = Field(..., min_length=2, description="Quiz title")
    description: Optional[str] = Field(None, description="Quiz description or instructions")
    quiz_type: str = Field(default="lesson_quiz", description="Type of quiz")
    passing_score_percentage: int = Field(default=70, ge=1, le=100)
    time_limit_minutes: Optional[int] = Field(None, ge=1)
    is_fallback: bool = Field(default=False)
    questions: List[GeneratedQuestion] = Field(default_factory=list)

    @field_validator("questions")
    @classmethod
    def validate_unique_questions(cls, v: List[GeneratedQuestion]) -> List[GeneratedQuestion]:
        if not v:
            raise ValueError("Quiz must contain at least one question.")
        seen = set()
        unique_questions = []
        for q in v:
            norm = q.question_text.strip().lower()
            if norm in seen:
                logger.warning("Duplicate question filtered out: %s", q.question_text)
                continue
            seen.add(norm)
            unique_questions.append(q)
        if not unique_questions:
            raise ValueError("Quiz has no unique questions after deduplication.")
        # Re-index order numbers sequentially
        for idx, q in enumerate(unique_questions, start=1):
            q.order_number = idx
        return unique_questions


# ---------------------------------------------------------------------------
# Deterministic Grounded Fallback Quiz Generator
# ---------------------------------------------------------------------------

def _clean_text_sentences(text: str) -> List[str]:
    """Splits raw text into clean, substantive educational sentences."""
    if not text:
        return []
    # Remove excessive whitespace
    cleaned = re.sub(r'\s+', ' ', text).strip()
    raw_sentences = re.split(r'(?<=[.!?])\s+', cleaned)
    valid_sentences = []
    for s in raw_sentences:
        s = s.strip()
        if len(s) >= 20 and s[0].isupper() and s.endswith(('.', '!', '?')):
            valid_sentences.append(s)
    return valid_sentences


def _rotate_options(correct_answer: str, distractors: List[str], target_index: int) -> List[str]:
    """
    Combines correct_answer with 3 distractors and places correct_answer
    at target_index (0, 1, 2, or 3) to vary answer keys deterministically.
    """
    opts = list(distractors[:3])
    idx = target_index % 4
    opts.insert(idx, correct_answer)
    return opts


def generate_grounded_fallback_quiz(
    lesson_title: str,
    module_title: Optional[str] = None,
    course_title: Optional[str] = None,
    content: str = "",
    summary: Optional[str] = None,
    learning_objectives: Optional[List[str]] = None,
    key_concepts: Optional[List[str]] = None,
    examples: Optional[List[str]] = None,
    misconceptions: Optional[List[str]] = None,
    practice_questions: Optional[List[Any]] = None,
    num_questions: int = 5,
    difficulty: str = "medium",
    passing_score_percentage: int = 70,
    time_limit_minutes: Optional[int] = None,
) -> GeneratedQuiz:
    """
    Generates a high-quality, strictly grounded multiple-choice quiz offline
    using lesson components: practice questions, key concepts, misconceptions,
    and learning objectives.

    Guarantees:
    - Exactly 4 unique options per question.
    - Exactly 1 correct answer belonging to the options.
    - No duplicate questions.
    - Grounded in source data; never invents unrelated facts.
    - is_fallback=True.
    """
    logger.info("Generating deterministic fallback assessment for lesson '%s'...", lesson_title)

    # Normalize inputs
    concepts = [c.strip() for c in (key_concepts or []) if isinstance(c, str) and c.strip()]
    miscons = [m.strip() for m in (misconceptions or []) if isinstance(m, str) and m.strip()]
    objectives = [o.strip() for o in (learning_objectives or []) if isinstance(o, str) and o.strip()]
    sentences = _clean_text_sentences(content)
    if not sentences and summary:
        sentences = _clean_text_sentences(summary)

    # Normalize practice questions
    norm_practice: List[Dict[str, str]] = []
    for pq in (practice_questions or []):
        if isinstance(pq, dict) and "question" in pq and "answer" in pq:
            norm_practice.append({
                "question": str(pq["question"]).strip(),
                "answer": str(pq["answer"]).strip(),
                "explanation": str(pq.get("explanation") or f"This is grounded directly in the lesson on {lesson_title}.").strip(),
            })
        elif hasattr(pq, "question") and hasattr(pq, "answer"):
            norm_practice.append({
                "question": str(pq.question).strip(),
                "answer": str(pq.answer).strip(),
                "explanation": str(getattr(pq, "explanation", "") or f"This is grounded directly in the lesson on {lesson_title}.").strip(),
            })

    # Plausible grounded fallback distractor templates
    # Formulated to be realistic, educational distractor alternatives
    contextual_distractor_pool = [
        "It applies only when explicitly formalized in a written agreement between both parties.",
        "It is evaluated strictly by the subjective intent of the initiator rather than the resulting impact.",
        "It is restricted solely to senior management and does not apply to peers, clients, or contractors.",
        "It can be safely disregarded if no formal objection is immediately voiced.",
        "It operates independently of any workplace policies, standards, or surrounding guidelines.",
        "It requires prior disciplinary history before any formal reporting or action may be initiated.",
        "It only occurs when physical actions take place, excluding verbal or non-verbal communication.",
        "It is considered fully acceptable if conducted offsite outside standard working hours.",
    ]

    # Combine distractor sources
    all_distractor_candidates: List[str] = []
    # 1. Misconceptions are prime distractor material (testing misconceptions)
    for m in miscons:
        if m not in all_distractor_candidates:
            all_distractor_candidates.append(m)
    # 2. Other practice question answers
    for p in norm_practice:
        if p["answer"] not in all_distractor_candidates:
            all_distractor_candidates.append(p["answer"])
    # 3. Contextual distractor pool
    for d in contextual_distractor_pool:
        if d not in all_distractor_candidates:
            all_distractor_candidates.append(d)

    questions_built: List[GeneratedQuestion] = []
    seen_question_prompts = set()

    def add_question(
        prompt: str,
        correct_ans: str,
        explanation: str,
        concept_tag: Optional[str] = None,
        custom_distractors: Optional[List[str]] = None,
    ) -> bool:
        norm_prompt = prompt.strip().lower()
        if norm_prompt in seen_question_prompts:
            return False

        # Select 3 unique distractors not matching correct_ans
        distractors: List[str] = []
        candidate_list = (custom_distractors or []) + all_distractor_candidates
        for cand in candidate_list:
            cand_clean = cand.strip()
            if (
                cand_clean.lower() != correct_ans.strip().lower()
                and cand_clean.lower() not in [d.lower() for d in distractors]
            ):
                distractors.append(cand_clean)
            if len(distractors) == 3:
                break

        # If still fewer than 3 distractors, pull unique contextual fallbacks
        if len(distractors) < 3:
            for fallback_d in contextual_distractor_pool:
                if (
                    fallback_d.lower() != correct_ans.strip().lower()
                    and fallback_d.lower() not in [d.lower() for d in distractors]
                ):
                    distractors.append(fallback_d)
                if len(distractors) == 3:
                    break

        if len(distractors) < 3:
            return False

        order_idx = len(questions_built) + 1
        options = _rotate_options(correct_ans, distractors, order_idx - 1)

        try:
            q_obj = GeneratedQuestion(
                question_text=prompt.strip(),
                question_type="multiple_choice",
                options=options,
                correct_answer=correct_ans.strip(),
                explanation=explanation.strip(),
                points=1,
                difficulty=difficulty,
                concept=concept_tag or lesson_title,
                order_number=order_idx,
            )
            questions_built.append(q_obj)
            seen_question_prompts.add(norm_prompt)
            return True
        except Exception as exc:
            logger.warning("Failed to validate fallback question '%s': %s", prompt, exc)
            return False

    # -----------------------------------------------------------------------
    # Strategy 1: Build from practice questions
    # -----------------------------------------------------------------------
    for pq in norm_practice:
        if len(questions_built) >= num_questions:
            break
        # Formulate concept tag from question or concepts
        matched_concept = next(
            (c for c in concepts if c.lower() in pq["question"].lower() or c.lower() in pq["answer"].lower()),
            concepts[0] if concepts else lesson_title,
        )
        add_question(
            prompt=pq["question"],
            correct_ans=pq["answer"],
            explanation=pq["explanation"],
            concept_tag=matched_concept,
        )

    # -----------------------------------------------------------------------
    # Strategy 2: Build from key concepts
    # -----------------------------------------------------------------------
    for idx, concept in enumerate(concepts):
        if len(questions_built) >= num_questions:
            break
        # Look for sentence defining or explaining this concept
        def_sentence = next(
            (s for s in sentences if concept.lower() in s.lower() and len(s) > 25),
            None,
        )
        if def_sentence:
            prompt = f"In the context of '{lesson_title}', which of the following best explains or defines '{concept}'?"
            correct_ans = def_sentence
            explanation = f"In this lesson, '{concept}' is explicitly described: {def_sentence}"
        else:
            prompt = f"Which of the following statements is TRUE regarding the core concept of '{concept}'?"
            correct_ans = f"'{concept}' is a key instructional principle analyzed in {lesson_title}."
            explanation = f"The lesson examines '{concept}' as an essential domain concept."

        # Use other concepts as distractors
        alt_concept_distractors = []
        for other_c in concepts:
            if other_c.lower() != concept.lower():
                alt_concept_distractors.append(
                    f"It refers strictly to '{other_c}', having no bearing on other aspects of {lesson_title}."
                )

        add_question(
            prompt=prompt,
            correct_ans=correct_ans,
            explanation=explanation,
            concept_tag=concept,
            custom_distractors=alt_concept_distractors,
        )

    # -----------------------------------------------------------------------
    # Strategy 3: Build from misconceptions (Identify false statements)
    # -----------------------------------------------------------------------
    for m in miscons:
        if len(questions_built) >= num_questions:
            break
        prompt = f"Which of the following represents a common MISCONCEPTION identified in the lesson on '{lesson_title}'?"
        correct_ans = m
        grounding = sentences[0] if sentences else f"the established standards of {lesson_title}"
        explanation = f"This statement is a common misconception identified in the lesson. In reality, {grounding}"

        # True statements as distractors
        true_distractors = []
        for obj in objectives:
            true_distractors.append(f"A core objective is to {obj.lower() if obj.startswith(('To ', 'Understand', 'Identify')) else obj}.")
        for s in sentences[:2]:
            if s.lower() != m.lower():
                true_distractors.append(s)

        matched_concept = next(
            (c for c in concepts if c.lower() in m.lower()),
            concepts[0] if concepts else lesson_title,
        )
        add_question(
            prompt=prompt,
            correct_ans=correct_ans,
            explanation=explanation,
            concept_tag=matched_concept,
            custom_distractors=true_distractors,
        )

    # -----------------------------------------------------------------------
    # Strategy 4: Build from learning objectives
    # -----------------------------------------------------------------------
    for obj in objectives:
        if len(questions_built) >= num_questions:
            break
        prompt = f"According to the lesson on '{lesson_title}', which of the following is a primary learning objective?"
        correct_ans = obj
        explanation = f"'{obj}' is explicitly defined as a fundamental learning goal for this lesson."
        add_question(
            prompt=prompt,
            correct_ans=correct_ans,
            explanation=explanation,
            concept_tag=concepts[0] if concepts else lesson_title,
        )

    # -----------------------------------------------------------------------
    # Strategy 5: Build from substantive sentences if still under target
    # -----------------------------------------------------------------------
    for s in sentences:
        if len(questions_built) >= num_questions:
            break
        prompt = f"Based on the educational text of '{lesson_title}', which of the following statements is accurate?"
        correct_ans = s
        explanation = f"This statement reflects the factual guidance provided in the lesson content: \"{s}\""
        add_question(
            prompt=prompt,
            correct_ans=correct_ans,
            explanation=explanation,
            concept_tag=concepts[0] if concepts else lesson_title,
        )

    if not questions_built:
        # Ultimate fail-safe fallback question grounded in lesson title
        prompt = f"What is the primary instructional focus of the lesson titled '{lesson_title}'?"
        correct_ans = f"Understanding the core definitions, guidelines, and principles of {lesson_title}."
        explanation = f"The entire lesson is dedicated to establishing clear principles for {lesson_title}."
        add_question(
            prompt=prompt,
            correct_ans=correct_ans,
            explanation=explanation,
            concept_tag=lesson_title,
        )

    return GeneratedQuiz(
        title=f"Quiz: {lesson_title}",
        description=f"Assessment of understanding for '{lesson_title}'",
        quiz_type="lesson_quiz",
        passing_score_percentage=passing_score_percentage,
        time_limit_minutes=time_limit_minutes,
        is_fallback=True,
        questions=questions_built[:num_questions],
    )


# ---------------------------------------------------------------------------
# LLM Quiz Generation
# ---------------------------------------------------------------------------

def generate_quiz_content(
    lesson_title: str,
    module_title: Optional[str] = None,
    course_title: Optional[str] = None,
    content: str = "",
    summary: Optional[str] = None,
    learning_objectives: Optional[List[str]] = None,
    key_concepts: Optional[List[str]] = None,
    examples: Optional[List[str]] = None,
    misconceptions: Optional[List[str]] = None,
    practice_questions: Optional[List[Any]] = None,
    num_questions: int = 5,
    difficulty: str = "medium",
    passing_score_percentage: int = 70,
    time_limit_minutes: Optional[int] = None,
) -> GeneratedQuiz:
    """
    Generates a complete, validated multiple-choice quiz for a lesson.
    - If Gemini API key is configured and not in TEST_MODE, requests structured JSON from Gemini.
    - If Gemini is unconfigured, rate-limited (HTTP 429), fails, or outputs invalid schema,
      falls back gracefully and deterministically to generate_grounded_fallback_quiz().
    """
    api_key, model_name = get_gemini_config()

    # Offline / Test Mode check
    if not api_key or os.getenv("TEST_MODE") == "true":
        logger.info("Using grounded deterministic quiz generator (offline mode or TEST_MODE).")
        return generate_grounded_fallback_quiz(
            lesson_title=lesson_title,
            module_title=module_title,
            course_title=course_title,
            content=content,
            summary=summary,
            learning_objectives=learning_objectives,
            key_concepts=key_concepts,
            examples=examples,
            misconceptions=misconceptions,
            practice_questions=practice_questions,
            num_questions=num_questions,
            difficulty=difficulty,
            passing_score_percentage=passing_score_percentage,
            time_limit_minutes=time_limit_minutes,
        )

    logger.info("Invoking Gemini model '%s' to generate assessment for '%s'...", model_name, lesson_title)

    # Format lesson educational material for context
    context_sections = []
    if summary:
        context_sections.append(f"Summary:\n{summary}")
    if learning_objectives:
        context_sections.append("Learning Objectives:\n" + "\n".join(f"- {o}" for o in learning_objectives))
    if key_concepts:
        context_sections.append("Key Concepts:\n" + "\n".join(f"- {c}" for c in key_concepts))
    if examples:
        context_sections.append("Illustrative Examples:\n" + "\n".join(f"- {e}" for e in examples))
    if misconceptions:
        context_sections.append("Common Misconceptions (use to craft plausible distractors):\n" + "\n".join(f"- {m}" for m in misconceptions))
    if practice_questions:
        pq_texts = []
        for pq in practice_questions:
            if isinstance(pq, dict):
                pq_texts.append(f"- Q: {pq.get('question')} | A: {pq.get('answer')} | Exp: {pq.get('explanation')}")
        if pq_texts:
            context_sections.append("Lesson Practice Questions:\n" + "\n".join(pq_texts))
    if content:
        context_sections.append(f"Main Lesson Text:\n{content[:4000]}")

    formatted_context = "\n\n---\n\n".join(context_sections)

    system_instruction = (
        "You are an expert educational assessment creator and instructional designer. "
        "Create a rigorous, multiple-choice quiz based EXCLUSIVELY on the provided lesson material.\n\n"
        "STRICT REQUIREMENTS:\n"
        f"1. Generate exactly {num_questions} questions.\n"
        f"2. Every question must be at '{difficulty}' difficulty level.\n"
        "3. Every question must have EXACTLY 4 options.\n"
        "4. Every question must have EXACTLY 1 correct answer.\n"
        "5. The 'correct_answer' MUST match one of the four options verbatim.\n"
        "6. Distractors (incorrect choices) must be plausible and preferably target common misconceptions from the lesson.\n"
        "7. Questions must test conceptual understanding and application, not trivial copy-pasting.\n"
        "8. Ground all questions and options strictly in the supplied lesson content. Never invent unrelated facts.\n"
        "9. Tag each question with its relevant concept from the lesson.\n"
        "10. Provide a clear pedagogical explanation justifying why the correct answer is right and why the distractors are wrong.\n"
        "11. Ensure NO duplicate questions.\n\n"
        "Return ONLY a valid JSON object matching this schema:\n"
        "{\n"
        f'  "title": "Quiz: {lesson_title}",\n'
        f'  "description": "Assessment of understanding for {lesson_title}",\n'
        '  "quiz_type": "lesson_quiz",\n'
        f'  "passing_score_percentage": {passing_score_percentage},\n'
        '  "questions": [\n'
        "    {\n"
        '      "question_text": "Clear, challenging question prompt",\n'
        '      "question_type": "multiple_choice",\n'
        '      "options": ["Option A", "Option B", "Option C", "Option D"],\n'
        '      "correct_answer": "Option A",\n'
        '      "explanation": "Why Option A is correct and why distractors are incorrect",\n'
        '      "points": 1,\n'
        f'      "difficulty": "{difficulty}",\n'
        '      "concept": "Relevant concept tag",\n'
        '      "order_number": 1\n'
        "    }\n"
        "  ]\n"
        "}"
    )

    user_prompt = (
        f"Course: {course_title or 'General Course'}\n"
        f"Module: {module_title or 'General Module'}\n"
        f"Lesson Title: {lesson_title}\n"
        f"Difficulty: {difficulty}\n"
        f"Number of Questions: {num_questions}\n\n"
        f"Lesson Educational Content:\n{formatted_context}\n\n"
        f"Generate exactly {num_questions} grounded multiple-choice questions matching the requested JSON structure."
    )

    try:
        raw_json = call_gemini_json(user_prompt, system_instruction=system_instruction)
        # Parse and validate questions list
        raw_questions = raw_json.get("questions", [])
        if not isinstance(raw_questions, list) or len(raw_questions) == 0:
            raise QuizGenerationError("Gemini returned no questions in response payload.")

        validated_questions: List[GeneratedQuestion] = []
        seen_prompts = set()

        for idx, q_raw in enumerate(raw_questions, start=1):
            if not isinstance(q_raw, dict):
                continue
            q_text = str(q_raw.get("question_text", "")).strip()
            if not q_text or q_text.lower() in seen_prompts:
                continue

            opts = q_raw.get("options", [])
            if not isinstance(opts, list) or len(opts) != 4:
                continue

            # Ensure clean string options
            clean_opts = [str(o).strip() for o in opts if str(o).strip()]
            if len(clean_opts) != 4 or len(set(o.lower() for o in clean_opts)) != 4:
                continue

            ans = str(q_raw.get("correct_answer", "")).strip()
            # Match answer to options
            matched_ans = next((o for o in clean_opts if o == ans), None)
            if not matched_ans:
                matched_ans = next((o for o in clean_opts if o.lower() == ans.lower()), None)
            if not matched_ans:
                continue

            expl = str(q_raw.get("explanation", "")).strip()
            if not expl:
                expl = f"Grounding explanation based on the lesson on {lesson_title}."

            concept_tag = str(q_raw.get("concept", "")).strip() or (key_concepts[0] if key_concepts else lesson_title)

            gq = GeneratedQuestion(
                question_text=q_text,
                question_type="multiple_choice",
                options=clean_opts,
                correct_answer=matched_ans,
                explanation=expl,
                points=int(q_raw.get("points", 1)),
                difficulty=str(q_raw.get("difficulty", difficulty)),
                concept=concept_tag,
                order_number=len(validated_questions) + 1,
            )
            validated_questions.append(gq)
            seen_prompts.add(q_text.lower())

            if len(validated_questions) == num_questions:
                break

        if len(validated_questions) < num_questions:
            raise QuizGenerationError(
                f"Gemini output only yielded {len(validated_questions)} valid questions (requested {num_questions})."
            )

        quiz = GeneratedQuiz(
            title=raw_json.get("title") or f"Quiz: {lesson_title}",
            description=raw_json.get("description") or f"Assessment of understanding for '{lesson_title}'",
            quiz_type=raw_json.get("quiz_type", "lesson_quiz"),
            passing_score_percentage=passing_score_percentage,
            time_limit_minutes=time_limit_minutes,
            is_fallback=False,
            questions=validated_questions,
        )
        logger.info("Successfully generated quiz via Gemini for '%s' (%d questions).", lesson_title, len(quiz.questions))
        return quiz

    except Exception as exc:
        logger.warning(
            "Gemini quiz generation failed for '%s': %s. Falling back to deterministic grounded generator.",
            lesson_title,
            exc,
        )
        return generate_grounded_fallback_quiz(
            lesson_title=lesson_title,
            module_title=module_title,
            course_title=course_title,
            content=content,
            summary=summary,
            learning_objectives=learning_objectives,
            key_concepts=key_concepts,
            examples=examples,
            misconceptions=misconceptions,
            practice_questions=practice_questions,
            num_questions=num_questions,
            difficulty=difficulty,
            passing_score_percentage=passing_score_percentage,
            time_limit_minutes=time_limit_minutes,
        )
